### ISSUE TITLE
Test Next.js build as part of CI process

### ISSUE THREAD

**Issue by jvorcak** [hazelcast/hive#211]
From time to time we have a problem with updating to the latest `core-ui` from .cloud (recently it was global styles with css-loader, or it used to be dependency on window and problems with SSR, etc) 

We usually catch these problems immediately when starting Next.js.
An idea is to create an empty Next.js project  with usage of our components as part of our CI pipeline.

**Comment by fantkolja** [comment]
I believe it's a duplication of #111
