### ISSUE TITLE
Restyle disabled tooltip

### ISSUE THREAD

**Issue by fantkolja** [hazelcast/hive#274]
![image](https://user-images.githubusercontent.com/13898415/120149065-d9c86480-c1f1-11eb-8900-da2f8eb6c2e2.png)
1. Should be one-liner
2. Add possibility to pass content as ReactNode???

**Comment by danad02** [comment]
Thanks to re-implemented portaling in https://github.com/hazelcast/hive/pull/314 this is fixed.
