### ISSUE TITLE
Accessibility outline fix

### ISSUE THREAD

**Issue by pawelklasa** [hazelcast/hive#319]
A good example of this is a bbc.co.uk website where the outline is hidden upon clicking but visible on TAB

**Comment by Sodik** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
Polyfill for Safari and old Edge  https://github.com/WICG/focus-visible

**Comment by fantkolja** [comment]
@Sodik Very nice CSS feature. Didn't know about it. But seems like it's behavior is not exactly what we are looking for and I assume may change and differ from browser to browser. We need to consider using `:focus-visible` or handle it with JS + custom root class...
![image](https://user-images.githubusercontent.com/13898415/126268658-2e74d686-b523-4c6e-aa78-3b67e6a2759d.png)
