### ISSUE TITLE
Warning secondary button needs to be added

### ISSUE THREAD

**Issue by pawelklasa** [hazelcast/hive#322]
![image](https://user-images.githubusercontent.com/11976919/122730247-ea5c7f80-d271-11eb-8aae-bdbddd6807f4.png)

we need to add a secondary button in red, there's also a wrong stroke on secondary buttons it needs to be 1px, not 2px.

![image-1](https://user-images.githubusercontent.com/11976919/122730276-f47e7e00-d271-11eb-8cba-dac328fdbbb4.png)

**Comment by danad02** [comment]
@pawelklasa The stroke width is already fixed.
