### ISSUE TITLE
Updating Typography to new brand

### ISSUE THREAD

**Issue by pawelklasa** [hazelcast/hive#366]
New font is Roboto

**Comment by fantkolja** [comment]
@utkukaratas @Sodik Will we break something on MC if we just replace Ubuntu with Roboto in the library?
@allfayn wants to kill Ubuntu very much :)

**Comment by fantkolja** [comment]
Need to update font-faces

**Comment by allfayn** [comment]
@pawelklasa What weight should I use for bold? (500 or 700)
https://google-webfonts-helper.herokuapp.com/fonts/roboto?subsets=latin

**Comment by pawelklasa** [comment]
Hi @allfayn for bold we will use 500 and we will delete 600 and 700 fonts

**Comment by allfayn** [comment]
500 bold:
![image](https://user-images.githubusercontent.com/135645/133239596-f0846b15-1d46-451e-bc36-1b5676d4cbe5.png)
![image](https://user-images.githubusercontent.com/135645/133239651-b91729ac-a91a-4155-b858-18d3a7f4f74f.png)
![image](https://user-images.githubusercontent.com/135645/133239754-304a699f-678b-468b-bac1-6348b08c07ec.png)

700 bold:
![image](https://user-images.githubusercontent.com/135645/133239988-2b5376d7-9dbf-4d11-8822-746182eac5be.png)
![image](https://user-images.githubusercontent.com/135645/133239937-db819b2a-db17-48c5-b16d-3e6da7eeacfa.png)
![image](https://user-images.githubusercontent.com/135645/133240050-ebd3dd83-d85d-4449-8ce3-d012e099f2d5.png)
